on: push

jobs:
  jobOne:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.foo.outputs.foo }}
    steps:
      - run: echo '::set-output name=foo::value=bar'
        id: foo
      
  jobTwo:
    needs: jobOne
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
        
  jobThree:
    needs: jobTwo
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.jobOne.outputs.foo }}
