name: "On Main"

on:
  push

jobs:
  be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mv -rf backend/ .
  fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mv -rf frontend/ .
