on:
  workflow_dispatch:
    inputs:
      cluster:
        type: string

jobs:
  dump_contexts_to_log:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ${{ contains(inputs.cluster, '[') && fromJson(format('["{0}"]', inputs.cluster)) || fromJson(inputs.clusters) }}
    steps:
      - run: echo ${{ matrix.cluster }}
