name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=abc::false'
        id: skip

      - run: echo I should run
        if: '!steps.skip.outputs.abc'

      - run: echo I should run
        if: '!steps.skip.outputs.def'

      - run: echo I should run
        if: '!steps.skip.outputs.abc && !steps.skip.outputs.def'
