name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONTAINS_PYTHON: ${{ contains(toJSON(github.event.commits.*.message), '[python]') }}
    steps:
      - run: echo ${{ env.CONTAINS_PYTHON }}
