name: "On Main"

on:
  push

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log -n 1

  build:
    uses: rethab/actions-test-repo/.github/workflows/partial.yml@main
    secrets:
      my-secret: ${{ secrets.TEST_SECRET }}

