name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '{"name":"Test Check","head_sha":"${{ github.sha }}"}' | gh api /repos/{owner}/{repo}/check-runs --input -

