name: "On Main"

on:
  pull_request:
  push:

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.github_token }}'
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ toJSON(job) }}'

