name: Workflow Dispatchy

on:
  push:

env:
  MY_ENV_VAR: bar

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - id: read-env
        run: |
          echo $GITHUB_SERVER_URL
      - run: echo "${{ format('{0} - {1}', github.actor, env.GITHUB_SERVER_URL) }}"
      - run: echo "${{ format('{0} - {1}', github.actor, env.MY_ENV_VAR) }}"

