name: "On Main"

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo hello, world
        if: contains(toJSON(github.event.commits.*.message), '[deploy]')

