name: "On Main"

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]


jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo hello, world
        if: github.event.action == 'edited' && contains(github.event.pull_request.title, '[deploy]')

