name: "On Main"

on:
  push:
  workflow_dispatch:

env:
  NAME: hans

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.NAME }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.NAME }}

