name: "On Main"

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo $GITHUB_SHA
      - run: echo '${{ toJSON(github.event) }}'
      - run: sleep 10
