name: "On Main"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo i am a tag
        if: startsWith(github.event.ref, 'refs/tags/')

