name: "On Main"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17.0.2-jdk
    steps:
      - uses: actions/checkout@v3
      - run: java --version
      - run: uname -a
      - run: ls -la
