name: "On Main"

on:
  workflow_dispatch:
    inputs:
      hubAddressGroupObject:
        type: choice
        description: 'Random description'
        required: true
        default: 'AZURE-EUW-XXXXX'
        options:
          - AZURE-EUW-XXXXX
          - AZURE-FRC-XXXXX
          - AZURE-USE-XXXXX
          - AZURE-FRC-XXXXX
          - AZURE-USE-XXXXX
          - AZURE-FRC-XXXXX
          - AZURE-USE-XXXXX

jobs:
  test:
    uses: rethab/actions-test-repo/.github/workflows/partial.yml@main
  two:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo hello

