name: "On Main"

on: push

jobs:
  partial:
    uses: rethab/actions-test-repo/.github/workflows/partial.yml@main
    with:
      enabled: true
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=abc::false'
        id: skip

      - run: echo I should run
        if: '!steps.skip.outputs.abc'

      - run: echo I should run
        if: '!steps.skip.outputs.def'

      - run: echo I should run
        if: '!steps.skip.outputs.abc && !steps.skip.outputs.def'
