on:
  workflow_dispatch:
    inputs:
      cluster:
        type: string
        default: 'europe'
      clusters:
        type: string

jobs:
  dump_contexts_to_log:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ${{ inputs.clusters && fromJson(inputs.clusters) || fromJson(format('[{{"name":"{0}"}}]', inputs.cluster))  }}
    steps:
      - run: echo ${{ toJson(matrix.cluster) }}
