name: "On Main"

on: issue_comment

jobs:
  test:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - run: echo '{"name":"Test Check","head_sha":"${{ github.sha }}"}' | gh api /repos/{owner}/{repo}/check-runs --input -

