name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=abc::false'
        id: skip
      - run: echo Skip Me
        if: 'steps.skip.outputs.abc != true && !steps.skip.outputs.def'
