name: Workflow Dispatchy

on:
  push:

env:
  MY_ENV_VAR: bar

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id)
