on:
  push:
  workflow_dispatch:
    inputs:
      cluster:
        type: string
        default: europe
      clusters:
        type: string

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ${{ inputs.cluster || fromJson(inputs.clusters) }}
    steps:
      - run: echo ${{ matrix.cluster }}
