name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ contains(toJSON(github.event.commits.*.message), '[python]') }}" == "true" ]]; then
            echo 'PYTHON_SET=yes' >> $GITHUB_ENV
          else
            echo 'PYTHON_SET=no' >> $GITHUB_ENV
          fi

      - run: echo ${{ env.PYTHON_SET }}
