on:
  push:
  workflow_dispatch:
    inputs:
      cluster:
        type: string
        default: europe

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ${{ fromJson(inputs.cluster) }}
    steps:
      - run: echo ${{ matrix.cluster }}
