name: "On Main"

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.PR_NUMBER }} - ${{ env.BUILD_NUMBER }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BUILD_NUMBER: ${{ github.event.number }}

