name: Workflow Dispatchy

on:
  push:

jobs:
  first:
    uses: ./.github/workflows/partial.yml
    with:
      my-input: first
  second:
    needs: first
    uses: ./.github/workflows/partial.yml
    with:
      my-input: second
      fail: true
  third:
    needs: second
    uses: ./.github/workflows/partial.yml
    if: failure() && needs.second.result == 'failure'
    with:
      my-input: third
