on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.first.outputs.env-name }}
    strategy:
      matrix:
        cluster: [dev, test]
    steps:
      - run: |
          envName="${{ matrix.cluster }}"
          echo "Environment: $envName"
          echo "env-name=$envName" >> $GITHUB_OUTPUT
  second:
    runs-on: ubuntu-latest
    needs: first
    environment: ${{ needs.first.outputs.env-name }}
    strategy:
      matrix:
        cluster: [dev, test]
    steps:
      - run: echo ${{ matrix.cluster }}
      - run: echo ${{ needs.first.outputs.env-name }}
