name: "On Main"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Find Paths
        id: find_path
        run: |
          all_paths=$(cat document.txt)
          echo "::set-output name=paths::$(echo ${all_paths})"

      - name: List
        id: list_path
        run: |
          var_paths=${{ steps.find_path.outputs.paths }}
          echo $var_paths
          echo nothing
          
          for part in ${var_paths[@]}; do 
             echo $part
          done
