on:
  workflow_dispatch:
    inputs:
      environment:
        description: The ENV
        type: choice
        options:
          - ''
          - production
        required: false

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.environment }}
