name: "On Main"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=skip-me::true'
        id: skip
      - run: echo nada
        id: skip2
      - run: echo I work
        if: '!steps.skip.outputs.skip-me'
      - run: echo I work2
        if: '!steps.skip2.outputs.skip-me'
