name: "On Main"

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
        continue-on-error: true
      - run: echo "${{ fromJSON(github.event) }}"
        continue-on-error: true
