name: "On Main"

on:
  workflow_dispatch:
    inputs:
      approval:
        description: "Do you approve?"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: action_required
          action_url: https://google.com