name: "On Main"

on:
  workflow_dispatch:
    inputs:
      approval:
        description: "Do you approve?"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello'
