name: "On Main"

on:
  push:

jobs:
  test:
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event_name != 'push' }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref != 'refs/heads/main' }}
