name: "On Main"

on:
  push:

concurrency:
  group: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.ref }}
    steps:
      - run: sleep 10
