name: "On Main"

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: action_required
          action_url: https://google.com