name: "On Main"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          for (( i=0; i<1; i++ )); do
            echo ${{github.event.commits}} | jq ".[$i]"
          done
