name: "Problem Matcher Test"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: echo "::add-matcher::.github/matcher.json"
      - run: |
          echo ".github/matcher.json:2: json error"
      - run: echo "::remove-matcher owner=test-matcher::"
