name: "On Main"

on:
  push:

jobs:
  collect_dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dirs.outputs.directories }}
    steps:
      - uses: actions/checkout@v2
      - id: dirs
        run: echo "::set-output name=directories::$(ls tests/)"

  run_tests:
    needs: collect_dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.collect_dirs.outputs.dirs) }}
    steps:
      - run: echo ${{ matrix.dir }}
