name: "On Main"

on: [pull_request]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first"
  second:
    needs: [first]
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: We require an action!
          conclusion: action_required
          action_url: https://podquotes.io
          details_url: https://digester.app
  third:
    needs: [second]
    runs-on: ubuntu-latest
    steps:
      - run: echo "third"
