name: "On Main"

on:
  push:
  workflow_dispatch:
    inputs:
      approval:
        description: "Do you approve?"
        required: true

concurrency:
  group: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - run: echo start
      - run: sleep 4000
      - run: echo end
