name: "On Main"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.commits}} | jq ".[0]"
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event.commits) }}' | jq ".[0]"
