on:
  workflow_call:
    inputs:
      greeting:
        description: "The greeting to use"
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.greeting }}
      cancel-in-progress: true
    steps:
      - run: echo before ${{ inputs.greeting }}
      - run: sleep 10
      - run: echo after ${{ inputs.greeting }}
