name: Gradle Build

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ${{ github.repository == 'actions-test-repo' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.environment }}
