name: Gradle Build

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  static-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.MY_SECRET }}

  dev-deployment:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - run: echo deploying to ${{ inputs.environment }}
