on:
  workflow_call:

jobs:
  greet:
    if: 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo hello

  meet:
    if: 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
