on:
  workflow_call:
    inputs:
      enabled:
        default: true
        description: "Enable or disable the workflow"
        required: false
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo I should run
        if: '!inputs.enabled'
