name: Reusable

on:
  workflow_call:
    inputs:
      my-input:
        description: optional input
        required: false
        type: string

jobs:
  jobA:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.my-input }}
