on:
  workflow_call:
    secrets:
      my-secret:
        required: false

concurrency:
  group: partial-${{ github.ref }}

jobs:
  greet:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: confirm
    steps:
      - run: echo ${{ secrets.TEST_SECRET }}
      - run: echo ${{ secrets.my-secret }}
