name: Gradle Build

on:
  workflow_call:
    inputs:
      my-input:
        description: optional input
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: inputs.my-input
        with:
            repository: ${{ inputs.my-input }}
      - uses: actions/checkout@v3
        if: ! inputs.my-input
