name: Multi Input

on:
  workflow_call:
    inputs:
      my-input:
        description: provide multiple values separated by comma
        required: true
        type: string

jobs:
  createMatrix:
    runs-on: ubuntu-latest
    matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - id: create-matrix
        run: |
          INPUTS="${{ inputs.my-input }} "
          echo "matrix={\"inputs\": [\"${INPUTS//,//\",\"}\"]}" >> $GITHUB_OUTPUT

  greet:
    needs: createMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.createMatrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.inputs }}
