name: Multi Input

on:
  workflow_call:
    inputs:
      my-input:
        description: no description
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.my-input }}
